logging:
  config: 'classpath:log4j2.yml'
server:
  port: 8091
spring:
  rabbitmq:
    consumer:
      exchange: query-executor-exchange
      request:
        queue: query-executor-queue
        routing-key: query-executor-routing-key
    username: admin
    password: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    addresses: dataquire-rabbit
  application:
    name: query-creator
eureka:
  client:
    service-url:
      defaultZone: "http://dataquire-eureka-server:8761/eureka"
  instance:
    ip-address: query-creator
    prefer-ip-address: true
secret:
  key: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==
