logging:
  config: 'classpath:log4j2.yml'
server:
  port: 8091
spring:
  rabbitmq:
    consumer:
      exchange: query-executor-exchange
      request:
        queue: query-executor-queue
        routing-key: query-executor-routing-key

    username: guest
    password: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  application:
    name: query-executor
eureka:
  client:
    service-url:
      defaultZone: "http://185.124.64.2:8761/eureka"
secret:
  key: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==
