logging:
  config: 'classpath:log4j2.yml'
server:
  port: 8091
spring:
  rabbitmq:
    consumer:
      exchange: query-executor-exchange
    username: guest
    password: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    addresses: localhost
  application:
    name: query-creator
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    ip-address: query-creator
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
secret:
  key: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==
