version: '3'

services:
  dataquire-eureka-server:
    build:
      dockerfile: ./Dataquire-Eureka-Server/Dockerfile
      context: .
    image: dataquire-eureka-server
    container_name: 'dataquire-eureka-server'
    ports:
      - "8761:8761"

  dataquire-gateway:
    build:
      dockerfile: ./Dataquire-Gateway/Dockerfile
      context: .
    image: dataquire-gateway
    container_name: 'dataquire-gateway'
    ports:
      - "8081:8081"

  authorization-service:
    build:
      context: ./
      dockerfile: Authorization-Service/Dockerfile
    image: authorization-service
    container_name: 'authorization-service'
    ports:
      - "8080:8080"

  instance-keeper:
    build:
      context: ./
      dockerfile: Instance-Keeper/Dockerfile
    image: instance-keeper
    container_name: 'instance-keeper'
    ports:
      - "8084:8084"

  database-manager:
    build:
      dockerfile: ./Database-Manager/Dockerfile
      context: .
    image: database-manager
    container_name: 'database-manager'
    ports:
      - "8085:8085"
  query-creator:
    build:
      dockerfile: ./Query-Creator/Dockerfile
      context: .
    image: query-creator
    container_name: 'query-creator'
    ports:
      - "8091:8091"
  query-executor:
    build:
      dockerfile: ./Query-Executor/Dockerfile
      context: .
    image: query-executor
    container_name: 'query-executor'
    ports:
      - "8086:8086"
  table-manager:
    build:
      dockerfile: ./Table-Manager/Dockerfile
      context: .
    image: table-manager
    container_name: 'table-manager'
    ports:
      - "8087:8087"
