spring:
  application:
    name: authorization-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
secret:
  key: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    ip-address: authorization-service
    prefer-ip-address: true
logging:
  config: 'classpath:log4j2.yml'