spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dataquire.dbms@gmail.com
    password: ccofrfvkfbzlidnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://dataquire:5432/users
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: authorization-service
springdoc:
  swagger-ui:
    config-url: /v3/api-docs
    url: /v3/api-docs
secret:
  key: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==
eureka:
  client:
    service-url:
      defaultZone: "http://dataquire-eureka-server:8761/eureka"
  instance:
    ip-address: authorization-service
    prefer-ip-address: true

logging:
  config: 'classpath:log4j2.yml'