spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nukem20r@gmail.com
    password: lizmspevdgnftous
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/udbms_users
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: authorization-service
springdoc:
  swagger-ui:
    config-url: /v3/api-docs
    url: /v3/api-docs
secret:
  key:

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8090/eureka"

logging:
  config: 'classpath:log4j2.yml'