springdoc:
  swagger-ui:
    config-url: /v3/api-docs
    url: /v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    ip-address: query-executor
    prefer-ip-address: true
secret:
  key: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==
  rsa:
    private: C:\Users\Roman\IdeaProjects\dataquire\Query-Executor\src\main\resources\dataquire-private.pem
logging:
  config: 'classpath:log4j2.yml'
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
server:
  port: 8086
feign:
  instance-keeper:
    address: http://instance-keeper:8084/
database:
  url: "jdbc:postgresql://localhost:5432/users"
  username: "postgres"
  password: "1337"
spring:
  rabbitmq:
    consumer:
      exchange: query-executor-exchange
      request:
        queue: query-executor-queue
        routing-key: query-executor-routing-key
      response:
        queue-response: query-executor-queue-response
        routing-key-response: query-executor-routing-key-response
    username: admin
    password: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    addresses: dataquire-rabbit
  application:
    name: query-executor
