spring:
  datasource:
    url: jdbc:postgresql://185.124.64.2:5432/udbms_users
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  application:
    name: database-manager
springdoc:
  swagger-ui:
    config-url: /v3/api-docs
    url: /v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: "http://185.124.64.2:8761/eureka"
  instance:
    prefer-ip-address: true
secret:
  key: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==
  rsa:
    public: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDiRRjRBbehnt57I29IA3D0EFA
      eaRhFMWKDOh7sE83TbUQgrHsADXzvupEOFg5AvRWAjPNDyPifiQ41J/onuMejETM
      3aA39abe1/AjmnrhYoDMBCubpERwDzI5K0U8JCEmMOg6hnT0J1+G0pIlTZdjVpx0
      auZrLVWGSQAimw1YwQIDAQAB
      -----END PUBLIC KEY-----
    private: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXQIBAAKBgQDDiRRjRBbehnt57I29IA3D0EFAeaRhFMWKDOh7sE83TbUQgrHs
      ADXzvupEOFg5AvRWAjPNDyPifiQ41J/onuMejETM3aA39abe1/AjmnrhYoDMBCub
      pERwDzI5K0U8JCEmMOg6hnT0J1+G0pIlTZdjVpx0auZrLVWGSQAimw1YwQIDAQAB
      AoGBAKkIQVWmsNZhDzDRK55IrV2PFDl2boF2AWZbzkXOnkxCornJIaHQdNNnQQEE
      bE+snCgV803bPrw3K3ztYecoI1DsJzEHgX93rrHpZcjjJCigl97aZVtJ2JluenfH
      7FlHWKAgcuCuCTCytW6nq5fVRbYid6buJBesrK8LHqZIOSeZAkEA5QcqxMPOGF6M
      BGvxFCxYTi8G5ds7XSwfZCcQvKocDvjETzc+vJo3vVFHDHEvINeBHWuKjKwGJu6U
      Fd2C+2stewJBANqQKmddojmLMUUwaUAb9rUnfKWg9EbAh6fDdGgwWmI8yC3cwVS9
      j2r+tTMnXw7WjUyIKZmjqX9NPHgi85p3d/MCQAw2uKIrqwcDq8Xkl8OypbbtrRl+
      +oh6fOYTa0IUdFCcFaP/1zmpo8VV20sfkhrXQ0x1WrsrxVw4Ju+Pk5ei3JcCQQCW
      eFApL6Zi1XhLOQQM9fOITjIbWU8zcpMyJXb7z+Y54byzDlsvev3E3KxlFkL0VTOc
      L9XsB2fG06bA0tdBTeSPAkB3tE/NEO/oU1d5ywxvPV6QR77ZB6mVb2u7xAHs6BVu
      XoPzKxfwLbgh9Y01YFfQENG4L2+vNlqjW3GemNcdk+nS
      -----END RSA PRIVATE KEY-----
logging:
  config: 'classpath:log4j2.yml'
server:
  port: 8085
