server:
  port: 8081
spring:
  application:
    name: dataquire-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  secret:

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8090/eureka"