server:
  port: 8081
spring:
  application:
    name: dataquire-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins:
              - "http://dataquire.ru:3000"
              - "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  secret: 0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA==

eureka:
  client:
    service-url:
      defaultZone: "http://dataquire-eureka-server:8761/eureka"
  instance:
    ip-address: dataquire-gateway
    prefer-ip-address: true