name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Docker-Compose Build
        run: docker compose build

      - name: Push dataquire-eureka-server to GHCR
        run: |
          docker tag dataquire-eureka-server ghcr.io/romekbulogin/dataquire-eureka-server:latest
          docker push ghcr.io/romekbulogin/dataquire-eureka-server:latest

      - name: Push dataquire-gateway to GHCR
        run: |
          docker tag dataquire-gateway ghcr.io/romekbulogin/dataquire-gateway:latest
          docker push ghcr.io/romekbulogin/dataquire-gateway:latest

      - name: Push authorization-service to GHCR
        run: |
          docker tag authorization-service ghcr.io/romekbulogin/authorization-service:latest
          docker push ghcr.io/romekbulogin/authorization-service:latest

      - name: Push database-manager to GHCR
        run: |
          docker tag database-manager ghcr.io/romekbulogin/database-manager:latest
          docker push ghcr.io/romekbulogin/database-manager:latest

      - name: Push table-manager to GHCR
        run: |
          docker tag table-manager ghcr.io/romekbulogin/table-manager:latest
          docker push ghcr.io/romekbulogin/table-manager:latest

      - name: Push instance-keeper to GHCR
        run: |
          docker tag instance-keeper ghcr.io/romekbulogin/instance-keeper:latest
          docker push ghcr.io/romekbulogin/instance-keeper:latest

      - name: Push query-creator to GHCR
        run: |
          docker tag query-creator ghcr.io/romekbulogin/query-creator:latest
          docker push ghcr.io/romekbulogin/query-creator:latest

      - name: Push query-executor to GHCR
        run: |
          docker tag query-executor ghcr.io/romekbulogin/query-executor:latest
          docker push ghcr.io/romekbulogin/query-executor:latest